name: PyPI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    pypi:
        name: "Install from PyPI"
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v3

            - name: "Install dependencies"
              run: |
                  python -m pip install --upgrade pip

            - name: "Install package"
              run: python -m pip install qpsolvers

            - name: "Test module import"
              run: python -c "import qpsolvers"

    testpypi:
        name: "Install from TestPyPI"
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v3

            - name: "Install dependencies"
              run: |
                  python -m pip install --upgrade pip

            - name: "Install package"
              run: python -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ qpsolvers

            - name: "Test module import"
              run: python -c "import qpsolvers"
